# Generated by Django 4.2.4 on 2024-01-03 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='title_ka',
        ),
    ]
