# Generated by Django 4.2.4 on 2024-01-20 15:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('UZ', 'Uzbek'), ('EN', 'English'), ('RU', 'Russian')], max_length=3)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='img/PdfFile/')),
                ('img', models.ImageField(upload_to='img/Pdfimg/')),
                ('price', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
