# Generated by Django 4.2.4 on 2023-08-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=256, null=True)),
                ('firtsname', models.CharField(max_length=256, null=True)),
                ('lastname', models.CharField(max_length=256, null=True)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('region', models.CharField(max_length=256, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('leaderboard_rate', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
