# Generated by Django 4.2.4 on 2023-08-23 11:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(upload_to='img/user_photos/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='region',
            field=models.CharField(choices=[(1, 'Tashkent'), (2, 'Samarkand')], default='UNKNOWN', max_length=255),
        ),
    ]
