# Generated by Django 4.2.4 on 2023-08-23 11:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_uz', models.CharField(max_length=256)),
                ('title_ru', models.CharField(max_length=256)),
                ('title_ka', models.CharField(max_length=256)),
                ('title_en', models.CharField(max_length=256)),
                ('link', models.EmailField(max_length=256)),
                ('image', models.ImageField(upload_to='img/banners/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
