# Generated by Django 4.2.4 on 2024-01-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='img',
            field=models.FileField(null=True, upload_to='img/tests/'),
        ),
        migrations.AddField(
            model_name='tests',
            name='question',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tests',
            name='correct_answer',
            field=models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')]),
        ),
        migrations.AlterField(
            model_name='tests',
            name='language',
            field=models.CharField(choices=[('UZ', 'Uzbek'), ('EN', 'English'), ('RU', 'Russian')], max_length=3),
        ),
        migrations.AlterField(
            model_name='tests',
            name='options',
            field=models.JSONField(null=True),
        ),
    ]
